name: Build Eseguibile Linux

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'  # Sostituisci con la versione di Python necessaria

    - name: Installazione dipendenze
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build eseguibile
      run: |
        pyinstaller --onefile --add-data "resources:resources" --hidden-import="PIL._tkinter_finder" --name "AccessiFCE" main.py

    - name: Upload eseguibile
      uses: actions/upload-artifact@v2
      with:
        name: AccessiFCELinux
        path: dist/AccessiFCE  # Sostituisci con il percorso corretto dell'eseguibile
